[book]
title = ""
authors = ["Shinren Pan"]
language = "zh_tw"
multilingual = false
src = "src"

[build]
build-dir = "book"

[preprocessor.alerts]
[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
git-repository-url = "https://github.com/shinrenpan"
git-repository-icon = "fa-github"
#no-section-label = true

[output.html.fold]
enable=true
